# default vlaues
ROTATE_DEFAULT = 0
ZOOM_DEFAULT = 0
FLIP_OPTIONS = ['None', 'X', 'Y', 'Both']
BLUR_DEFAULT = 0
CONTRAST_DEFAULT = 0
EFFECT_OPTIONS = ['None', 'Emboss', 'Find edges', 'Contour', 'Edge enhance']
BRIGHTNESS_DEFAULT = 1
VIBRANCE_DEFAULT = 1
GRAYSCALE_DEFAULT = False
INVERT_DEFAULT = False

# colors
BACKGROUND_COLOR = '#242424'
WHITE = '#FFF'
GRAY = 'gray'
BLUE = '#1F6AA5'
DARK_GRAY = '#4A4A4A'
CLOSE_RED = '#8A0606'
SLIDER_BG ='#64686B'